export const seedAccounts = [
  { memberId: 1, username: 'fadilah.maulidiyah', passwordEnv: 'SEED_PASSWORD_FADILAH_MAULIDIYAH', displayName: 'Fadilah P. L. Maulidiyah', divisionRole: 'Sekretaris', accountType: 'member' },
  { memberId: 2, username: 'daniel.manalu', passwordEnv: 'SEED_PASSWORD_DANIEL_MANALU', displayName: 'Daniel S. Manalu', divisionRole: 'Bendahara', accountType: 'member' },
  { memberId: 3, username: 'maura.ramadhani', passwordEnv: 'SEED_PASSWORD_MAURA_RAMADHANI', displayName: 'Maura S. Ramadhani', divisionRole: 'Koordinator Desa', accountType: 'member' },
  { memberId: 4, username: 'yance.panjaitan', passwordEnv: 'SEED_PASSWORD_YANCE_PANJAITAN', displayName: 'Yance A. N. Panjaitan', divisionRole: 'Wakil Koordinator Desa', accountType: 'member' },
  { memberId: 5, username: 'zaki.alhilmi', passwordEnv: 'SEED_PASSWORD_ZAKI_ALHILMI', displayName: 'M. Zaki Al Hilmi', divisionRole: 'Acara', accountType: 'member' },
  { memberId: 6, username: 'syakila.nayla', passwordEnv: 'SEED_PASSWORD_SYAKILA_NAYLA', displayName: 'Syakila Gian Nayla', divisionRole: 'Acara', accountType: 'member' },
  { memberId: 7, username: 'aditya.akbar', passwordEnv: 'SEED_PASSWORD_ADITYA_AKBAR', displayName: 'Aditya Akbar', divisionRole: 'Humas', accountType: 'member' },
  { memberId: 8, username: 'niquita.zahara', passwordEnv: 'SEED_PASSWORD_NIQUITA_ZAHARA', displayName: 'Niquita A. Az Zahara', divisionRole: 'Humas', accountType: 'member' },
  { memberId: 9, username: 'akbar.kusuma', passwordEnv: 'SEED_PASSWORD_AKBAR_KUSUMA', displayName: 'Akbar B. Kusuma', divisionRole: 'Perkap', accountType: 'member' },
  { memberId: 10, username: 'iqbal.faizin', passwordEnv: 'SEED_PASSWORD_IQBAL_FAIZIN', displayName: 'Iqbal A. Faizin', divisionRole: 'Perkap', accountType: 'member' },
  { memberId: 11, username: 'm.aditya.akbar', passwordEnv: 'SEED_PASSWORD_M_ADITYA_AKBAR', displayName: 'M. Aditya Akbar', divisionRole: 'Perkap', accountType: 'member' },
  { memberId: 12, username: 'christama.ezra', passwordEnv: 'SEED_PASSWORD_CHRISTAMA_EZRA', displayName: 'Christama Ezra Y.', divisionRole: 'DDM', accountType: 'member' },
  { memberId: 13, username: 'albert.pasunda', passwordEnv: 'SEED_PASSWORD_ALBERT_PASUNDA', displayName: 'Albert J. Pasunda', divisionRole: 'DDM', accountType: 'member' },
  { memberId: null, username: 'admin.mmd33', passwordEnv: 'SEED_PASSWORD_ADMIN_MMD33', displayName: 'Administrator MMD FILKOM 33', divisionRole: 'Administrator', accountType: 'admin' },
]
