export const seedAccounts = [
  { memberId: 1, username: 'fadilah.maulidiyah', password: 'Fadilah#Laut33!', displayName: 'Fadilah P. L. Maulidiyah', divisionRole: 'Sekretaris', accountType: 'member' },
  { memberId: 2, username: 'daniel.manalu', password: 'Daniel#Ombak33!', displayName: 'Daniel S. Manalu', divisionRole: 'Bendahara', accountType: 'member' },
  { memberId: 3, username: 'maura.ramadhani', password: 'Maura#Pesisir33!', displayName: 'Maura S. Ramadhani', divisionRole: 'Koordinator Desa', accountType: 'member' },
  { memberId: 4, username: 'yance.panjaitan', password: 'Yance#Samudra33!', displayName: 'Yance A. N. Panjaitan', divisionRole: 'Wakil Koordinator Desa', accountType: 'member' },
  { memberId: 5, username: 'zaki.alhilmi', password: 'Zaki#Bahari33!', displayName: 'M. Zaki Al Hilmi', divisionRole: 'Acara', accountType: 'member' },
  { memberId: 6, username: 'syakila.nayla', password: 'Syakila#Karang33!', displayName: 'Syakila Gian Nayla', divisionRole: 'Acara', accountType: 'member' },
  { memberId: 7, username: 'aditya.akbar', password: 'Aditya#Senja33!', displayName: 'Aditya Akbar', divisionRole: 'Humas', accountType: 'member' },
  { memberId: 8, username: 'niquita.zahara', password: 'Niquita#Nautika33!', displayName: 'Niquita A. Az Zahara', divisionRole: 'Humas', accountType: 'member' },
  { memberId: 9, username: 'akbar.kusuma', password: 'Akbar#Pantai33!', displayName: 'Akbar B. Kusuma', divisionRole: 'Perkap', accountType: 'member' },
  { memberId: 10, username: 'iqbal.faizin', password: 'Iqbal#Pasang33!', displayName: 'Iqbal A. Faizin', divisionRole: 'Perkap', accountType: 'member' },
  { memberId: 11, username: 'm.aditya.akbar', password: 'MAditya#Surut33!', displayName: 'M. Aditya Akbar', divisionRole: 'Perkap', accountType: 'member' },
  { memberId: 12, username: 'christama.ezra', password: 'Christama#Biru33!', displayName: 'Christama Ezra Y.', divisionRole: 'DDM', accountType: 'member' },
  { memberId: 13, username: 'albert.pasunda', password: 'Albert#Horizon08!', displayName: 'Albert J. Pasunda', divisionRole: 'DDM', accountType: 'member' },
  { memberId: null, username: 'admin.mmd33', password: 'Admin#Pulupulu33', displayName: 'Administrator KKN 08', divisionRole: 'Administrator', accountType: 'admin' },
]
