CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER UNIQUE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  display_name TEXT NOT NULL,
  account_type TEXT NOT NULL CHECK (account_type IN ('member', 'admin')),
  division_role TEXT NOT NULL,
  must_change_password BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX idx_users_username_ci
  ON users (LOWER(username));

CREATE INDEX idx_users_username_active
  ON users (LOWER(username), is_active);

CREATE TABLE sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_sessions_token_expires
  ON sessions (token_hash, expires_at);

CREATE TABLE private_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '' CHECK (CHAR_LENGTH(title) <= 60),
  body TEXT NOT NULL DEFAULT '' CHECK (CHAR_LENGTH(body) <= 1500),
  closing TEXT NOT NULL DEFAULT '' CHECK (CHAR_LENGTH(closing) <= 80),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent')),
  unlock_at TIMESTAMPTZ NOT NULL DEFAULT TIMESTAMPTZ '2026-08-08T19:00:00+07:00',
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sent_at TIMESTAMPTZ,
  CHECK (sender_user_id <> recipient_user_id)
);

CREATE UNIQUE INDEX idx_private_messages_active_draft
  ON private_messages (sender_user_id, recipient_user_id)
  WHERE status = 'draft';

CREATE INDEX idx_private_messages_recipient_status
  ON private_messages (recipient_user_id, status, sent_at);

CREATE TABLE app_settings (
  setting_key TEXT PRIMARY KEY,
  setting_value TEXT NOT NULL,
  updated_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO app_settings (setting_key, setting_value)
VALUES
  ('global_message_access', 'locked'),
  ('global_message_release_at', '2026-08-08T19:00:00+07:00')
ON CONFLICT (setting_key) DO NOTHING;
